project:
  type: website

website:
  title: "Hello world"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



